name: "upload"

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: upload-workflow
  cancel-in-progress: true

jobs:
  upload-files:
    name: upload
    runs-on: ubuntu-latest
    steps:
      - name: Clone local repository
        uses: actions/checkout@v2
      - name: Get version
        run: |
          ver=$(cat addon.xml | grep plugin.audio.music163 | grep -o "[0-9]\.[\.0-9]*")
          echo "VERSION=$ver" >> $GITHUB_ENV
      - name: Move files
        run: |
          mkdir plugin.audio.music163
          rm -rf .github .git .gitignore public
          shopt -s extglob
          mv !(plugin.audio.music163) plugin.audio.music163
      - name: Upload addon
        uses: actions/upload-artifact@v2
        with:
          name: plugin.audio.music163-${{ env.VERSION }}-python3
          path: ./
      - name: Change python version
        run: |
          sed -i "s/3\.0\.0/2\.7\.0/g" ./plugin.audio.music163/addon.xml
          sed -i "/script\.module\.qrcode/d" ./plugin.audio.music163/addon.xml
      - name: Upload addon
        uses: actions/upload-artifact@v2
        with:
          name: plugin.audio.music163-${{ env.VERSION }}-python2
          path: ./
